# Generated by Django 2.1.10 on 2019-08-02 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190802_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionflownode',
            name='allowed_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='questionflownode',
            name='answer_options_display',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='questionprompt',
            name='allowed_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='questionprompt',
            name='answer_options_display',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='questionprompt',
            name='next_flow_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('INTRO', 'INTRO'), ('ASAP', 'ASAP'), ('STRUCTURED', 'STRUCTURED')], max_length=25), null=True, size=None),
        ),
    ]
