# Generated by Django 2.1.10 on 2019-08-06 00:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190802_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text_to_forward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionprompt',
            name='confirmation_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionprompt',
            name='success_handlers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_outbound_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
