# Generated by Django 2.1.10 on 2019-08-06 00:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190806_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionflownode',
            name='success_handlers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), null=True, size=None),
        ),
    ]
