# Generated by Django 2.1.10 on 2019-08-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitation',
            name='text',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
