# Generated by Django 2.1.10 on 2019-08-07 16:43

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190807_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expiration_date',
            field=models.DateTimeField(default=base.utils.get_expiration_date),
        ),
    ]
