# Generated by Django 2.2.3 on 2019-09-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_event_crew_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
